name: Package exe with PyInstaller - Windows

on:
  pull_request:
    branches: [ main ]
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'Eden Burner.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Eden Burner'
