name: Package exe with PyInstaller - Windows

on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
    - uses: actions/upload-artifact@v4
      with:
        name: burner
        path: |
          dist